### PR TITLE
Captionify can have ES5 methods

### PR DESCRIPTION
**Pull request by luck2011**
Due to its target browsers, Captionify may use ES5 APIs.:)

### CODE REVIEW

**Comment by bolatovumar** [comment]
Suggested changes make sense but I get this error when opening the test 'examples.html' file. Probably has something do to with the fact that querySelectorAll returns a NodeList as opposed to an HTMLCollection reurned by getElementsByTagName and the company.

error

**Comment by luck2011** [comment]
Glad to hear! It was a bug and I have fixed this in the following commits. So please give another try from my forked repo.Thanks!

**Comment by bolatovumar** [comment]
Seems fine now. Will probably have to drop support for Firefox <3.5 since no querySelectorAll support. But it's no big deal.

**Comment by luck2011** [comment]
Cheers！

**Pull request merged**
